periodic_clear_jobs:
  command: "SolidQueue::Job.clear_finished_in_batches"
  priority: 2
  schedule: at 5am every day
publish_photo:
  class: PublishPhotoJob
  queue: default
  args: []
  schedule: "0 */2 9-17 * *"
